# Generated by Django 5.0.6 on 2024-07-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(default=0, max_length=36, primary_key=True, serialize=False)),
                ('album', models.CharField(default='Unknown Album', max_length=200)),
                ('artist', models.CharField(default='Unknown Artist', max_length=200)),
                ('title', models.CharField(default='Untitled', max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('lyrics', models.TextField(default='')),
            ],
            options={
                'db_table': 'songs',
            },
        ),
    ]
