# Generated by Django 5.0.6 on 2024-06-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_url', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('featured_artist', models.CharField(max_length=200)),
                ('lyrics', models.TextField()),
                ('media', models.TextField()),
                ('rank', models.IntegerField()),
                ('release_date', models.DateField()),
                ('song_title', models.CharField(max_length=200)),
                ('song_url', models.CharField(max_length=200)),
            ],
        ),
    ]
