# Generated by Django 5.0.6 on 2024-06-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiosity_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='featured_artist',
        ),
        migrations.AddField(
            model_name='song',
            name='adverbs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='corpus',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='featured_artists',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='song',
            name='nouns',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='unique_word_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='verbs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='word_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='writers',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
