# Generated by Django 5.0.6 on 2024-06-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiosity_app', '0002_remove_song_featured_artist_song_adverbs_song_corpus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='media',
            field=models.TextField(default='[]'),
        ),
    ]
