# Generated by Django 5.0.6 on 2024-07-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiosity_app', '0003_image_delete_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
