# Generated by Django 5.0.6 on 2024-07-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiosity_app', '0003_alter_song_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='song',
            name='adverbs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='song',
            name='featured_artists',
        ),
        migrations.RemoveField(
            model_name='song',
            name='media',
        ),
        migrations.RemoveField(
            model_name='song',
            name='nouns',
        ),
        migrations.RemoveField(
            model_name='song',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='unique_word_counts',
        ),
        migrations.RemoveField(
            model_name='song',
            name='verbs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='word_counts',
        ),
        migrations.RemoveField(
            model_name='song',
            name='writers',
        ),
        migrations.RemoveField(
            model_name='song',
            name='year',
        ),
    ]
