# Generated by Django 5.0.6 on 2024-07-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiosity_app', '0004_rename_song_title_song_title_remove_song_adverbs_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='songs',
        ),
    ]
