# Generated by Django 5.0.6 on 2024-07-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiosity_app', '0006_alter_song_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.CharField(default=0, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(default='Unknown Album', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(default='Unknown Artist', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.AlterModelTable(
            name='song',
            table='songs',
        ),
    ]
