# Generated by Django 5.0.6 on 2024-07-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiosity_app', '0007_remove_song_id_song_song_id_alter_song_album_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='all_songs',
        ),
    ]
