# Generated by Django 5.0.6 on 2024-07-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiosity_app', '0010_alter_song_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='songs',
        ),
    ]
